apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-role-binding.yml
  - service-account.yml
  - daemonset.yml
  - service.yml
  - ingress.yml
  - service-monitor.yml
